# BLE GATT Messages #

Communication between Gateway and Sensor is done via Bluetooth Low Energy. It uses the Nordic UART service which itself uses the GATT protocol. 

Three types of messages are used.

1. The Gateway sends control messages to the sensor to set or read configuration or start transmission of logged data.
2. The Sensor responds to control messages via response messages. This message type transports state information or configuration data.
3. When the Gateway requests the Sensor to send logged data, this data is send by data messages. To Transport all data many data messages are repeated. The end of data is signalled by a response message.

All messages are distinguished by the first byte. All messages must be padded by nullbytes to a minimum length of 11 bytes. This requirement is introduced by the Ruuvi firmware. The padding bytes are not shown in the following description of the messages.

## Control messages ##

Control messages are indicated by the byte `0xFA` as the first byte. This byte is repeated as the second byte. The type of the message distinguished by the third byte. The general structure of a control message is show in the following table.

| Header | Header | Type | Parameter |
|-|-|-|-|
| `0xFA` | `0xFA` | XX | Zero or more Parameter |

### Start transmitting last sample (`0x03`) ###

This message starts transmitting the last sample of acceleration data. This sample consists of 32 tuples of (X,Y,Z) values. It is taken from RAM and transmitted to the gateway by using data messages. The transmission of the data is followed by a control message which signals the end of the data. 

This message takes no parameters. It's concrete content is: `0xFA 0xFA 0x03`.

When acceleration logging is not active, the Sensor responds a state message containing an error code.

### Start transmitting logged data (`0x05`) ###

This message starts transmitting the logged acceleration data from the ringbuffer. The data includs the last page which is not complety full and is not yet written to flash. The transmission of the data is followed by a control message which signals the end of the data. After requesting the logged data the ringbuffer is empty.

This message takes no parameters. It's concrete content is: `0xFA 0xFA 0x05`.

When acceleration logging is not active, the Sensor responds with a state message containing an error code.

### Set configuration of acceleration sensor (`0x06`) ###

This message is used to set the configuration of the acceleration sensor (LIS2DH12). The message takes 8 Parameters. The Sensor responds to this message with a state response. The parameters are as follows.

| Parameter | Description |
|-|-|
| P1 | Rate of sampling. Allowable values are 1, 10, 25, 50, 100, 200. |
| P2 | Resolution. Allowable values are 8, 10, 12. |
| P3 | Scale. Allowable values are 2, 4, 8, 16. |
| P4 | DSP function. See datasheet of LIS2DH12. |
| P5 | DSP parameter. See datasheet of LIS2DH12. |
| P6 | Mode of operation. Allowable values are `0xF2`, `0xF3`, `0xF4`. See datasheet of LIS2DH12. |
| P7 | Reserved. Set to `0x00`. |
| P8 | Reserved. Set to `0x00`. |

All values from P1 to P6 can be set to `0xFF` which means 'do not change this values'.

The concrete content of this message is `0xFA 0xFA 0x06 P1 P2 P3 P4 P5 P6 P7 P8`.

### Read configuration of acceleration sensor (`0x07`) ###

This message is used to read the configuration of the acceleration sensor (LIS2DH12). The messag takes no parameters. The Sensor responds to this message either by a state message containing an error code or by a response message which transmits the configuration.

The concrete content of this message is: `0xFA 0xFA 0x07`.

### Set system time (`0x08`) ###

This message is used to set the RTC of the sensor to a timestamp which is part of the message. The timestamp must be a 8 byte UNIX timestamp. It must be transmitted in little-endian byte sequence. The sensor responds to this message with a state response.

The concrete content of this message is `0xFA 0xFA 0x08 XX XX XX XX XX XX XX XX`.

### Read system time (`0x09`) ###

This message is used to read the RTC of the sensor. The sensor responds to this message with a state response containing an error code or with a timestamp response.

The concrete content of this message is `0xFA 0xFA 0x09`.

### Control acceleration logging (`0x0A`) ###

This message is used to activate or deactivate acceleration logging. It takes one parameter. The parameter is interpreted as a boolean value. If it maps to true acceleration logging is activated. If it maps to false acceleration logging is deactivated. The sensor responds to this message using a state response. Sending a control message to activate logging when it is already active results in an error. The same condition is when sending a message to deactivate logging.

The concrete content of this message is `0xFA 0xFA 0x0A XX`. Where `XX` can be `0x00` or `0x01`.

### Query state of acceleration logging (`0x0B`) ###

This message is used to query the state of acceleration logging. The sensor responds to this message with a state response. When logging is active, the response contains the state `RD_SUCCESS` when logging is not active the state is `RD_ERROR_NOT_INITIALIZED`.

The concrete content of this message is `0xFA 0xFA 0x0B`.

## Response messages ##

Response messages are indicated by the byte `0xFB` as the first byte. The type of the message distinguished by the second byte. The general structure of a response message is show in the following table.

| Header | Type | State | Parameter |
|-|-|-|-|
| `0xFB` | XX | State | Zero or more Parameter |

State must be interpreted as a bitfield. The bits represent the different error conditions. The following table show the error conditions.

| Value | Error |
|-|-|
| 0       | RD_SUCCESS: No error
| 1       | RD_ERROR_INTERNAL: Internal Error
| 2       | RD_ERROR_NO_MEM: No Memory for operation
| 4       | RD_ERROR_NOT_FOUND: Not found
| 8       | RD_ERROR_NOT_SUPPORTED: Not supported
| 16      | RD_ERROR_INVALID_PARAM: Invalid Parameter
| 32      | RD_ERROR_INVALID_STATE: Invalid state, operation disallowed in this state
| 64      | RD_ERROR_INVALID_LENGTH: Invalid Length
| 128     | RD_ERROR_INVALID_FLAGS: Invalid Flags
| 256     | RD_ERROR_INVALID_DATA: Invalid Data
| 512     | RD_ERROR_DATA_SIZE: Invalid Data size
| 1024    | RD_ERROR_TIMEOUT: Operation timed out
| 2048    | RD_ERROR_NULL: Null Pointer
| 4096    | RD_ERROR_FORBIDDEN: Forbidden Operation
| 8192    | RD_ERROR_INVALID_ADDR: Bad Memory Address
| 16384   | RD_ERROR_BUSY: Flash Busy
| 32768   | RD_ERROR_RESOURCES: Not enough resources for operation
| 65535   | RD_ERROR_NOT_IMPLEMENTED: Not implemented yet
| 131072  | RD_ERROR_SELFTEST: Self-test fail
| 262144  | RD_state_MORE_AVAILABLE: Driver has more data queued
| 524288  | RD_ERROR_NOT_INITIALIZED: Driver is not initialized.
| 1048576 | RD_ERROR_NOT_ACKNOWLEDGED: Ack was expected but not received
| 2097152 | RD_ERROR_NOT_ENABLED: Driver is not enabled

### State response (`0x00`) ###

This message is used to return a state code to the gateway when no other information is available.

The concrete content of this message is `0xFB 0x00 SS`. Where `SS` is the state code.

### End of data message (`0x03`, `0x05`) ###

This message is send to the gateway after returning data. It signals the end of the transmission. The type byte (`0x03`, `0x05`) maps to the type of data requested. This message contains two parameters. The current configuration os the acceleration sensor is the first parameter. The CRC16 value of the transmitted data is the seconds parameter.

To compute the CRC16 value the polynom `0x11021` with the initial value `0xFFFF` is used. The output bytes are not reversed and not XOR'd.

The concrete content of this message is `0xFB 0x03/0x05 P1 P2 P3 P4 P5 P6 P7 P8 CRC1 CRC2`. The values P1 to P8 map to the same values as described earlier.

### Configuration response (`0x07`) ###

This message is send to the gateway after requesting the current configuration. The message contains one parameter containing the current configuration.

The concrete content of this message is `0xFB 0x07 P1 P2 P3 P4 P5 P6 P7 P8`. The values P1 to P8 map to the same values as described earlier.

### Timestamp response (`0x09`) ###

This message is send to the gateway after requesting the system time. The message contains one parameter. The parameter is a 8 byte value containing the current timestamp. The bytes are transfered in little-endian sequence.

The concrete content of this message is `0xFB 0x09 XX XX XX XX XX XX XX XX`. 

## Data message ##

Data messages are used to transfer logged acceleration data. A data message starts with the byte `0xFC`. After the start byte there follows up to 19 bytes of data.

The concrete content of this message is `0xFC XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX`. 
